@startuml
skin rose

[*] -> A
A -> B : [ guard1() ] / action1()
A --> C : [ guard2() ] / action2()
A --> D : event

A : entry / actionA()
B : entry / actionB()
C : entry / actionC()
D : entry / actionD()

'[code] private:
'[code] bool guard1() { return true; }
'[code] bool guard2() { return true; }
'[code] void action1() { FSM_LOGD("[ACTION %s]\n", __func__); }
'[code] void action2() { FSM_LOGD("[ACTION %s]\n", __func__); }
'[code] void actionA() { FSM_LOGD("[ACTION %s]\n", __func__); }
'[code] void actionB() { FSM_LOGD("[ACTION %s]\n", __func__); }
'[code] void actionC() { FSM_LOGD("[ACTION %s]\n", __func__); }
'[code] void actionD() { FSM_LOGD("[ACTION %s]\n", __func__); }

@enduml
